### ISSUE TITLE
0.3.0.0 Status NotSupported in JF 10.9.1

### ISSUE THREAD

**Issue by JellyFusion** [CherryFloors/jellyfin-plugin-cinemamode#12]
0.2.0.0 shows status as 'Superceded' and 0.3.0.0 installs, when status shows 'Restart', settings are available as expected.

However, status will change on restart Status to 'NotSupported' and there are no settings only 'Uninstall' option.

No other system changes aside from JF update, 0.2.0.0 stopped working, and 0.3.0.0 appeared as part of Plugin update scheduled task.

<img width="592" alt="Screenshot 2024-05-23 at 7 29 21 PM" src="https://github.com/CherryFloors/jellyfin-plugin-cinemamode/assets/170616725/15d76a96-6d98-47d4-ada4-f27f538fdb92">
<img width="591" alt="Screenshot 2024-05-23 at 7 29 30 PM" src="https://github.com/CherryFloors/jellyfin-plugin-cinemamode/assets/170616725/77053dc4-b211-45cd-9078-336ddec62640">
<img width="292" alt="Screenshot 2024-05-23 at 7 30 36 PM" src="https://github.com/CherryFloors/jellyfin-plugin-cinemamode/assets/170616725/9faa5eba-3688-4f7b-96fc-0e2c093e18f9">

**Comment by CherryFloors** [comment]
Try updating to Jellyfin 10.9.2, it was released shortly after 10.9.1. It is the only version I have tested this plugin with currently.

The change that broke v0.2.0.0 of this plugin was introduced in 10.9.0. I assumed that 0.3.0.0 would be compatible with >10.9. I'm not sure why this is not working with 10.9.1 and a fix for that may take a little while.

**Comment by JellyFusion** [comment]
yes this 100% resolved issue, many thanks, and apologies - I literally tried everything else, removed repository re-added, disabled all other plugins etc. I didn't realise there was a 10.9.2

**Comment by CherryFloors** [comment]
Thats good to hear, and there's no need for apologies. This is a legitimate issue and I'm glad you didn't need to wait on me for a fix. I wont go into too much detail but I compiled the new version of the plugin against binaries that were not compatible with 10.9.0 and 10.9.1 and the manifest does not reflect that so I'll need to update that at some point. Until then, this thread may help anyone who ran into the same problem. I'm happy that people are using this plugin and I hope you enjoy it.

**Comment by JellyFusion** [comment]
Absolutely - very happy with it, the only thing that would make it better for my purposes is if, similar to the ratings filter, it could filter to trailers for movies of same decade, or to only movies within ‘x’ months of release date, or same genre. I know I’m being hyper specific but would love to just see 80’s horror trailers if I was doing a Nightmare on Elm street marathon for example.

**Comment by CherryFloors** [comment]
> Absolutely - very happy with it, the only thing that would make it better for my purposes is if, similar to the ratings filter, it could filter to trailers for movies of same decade, or to only movies within ‘x’ months of release date, or same genre. I know I’m being hyper specific but would love to just see 80’s horror trailers if I was doing a Nightmare on Elm street marathon for example.

That type of configuration was always the ultimate goal, for both Pre-Rolls and Trailers. I had a few ideas how I would approach it but providing that sort of configuration in an intuitive way can be tough. I had to do some extra work to provide more stable support for Pre-Roll intros so I took a first pass at expanding configuration in the newest release.

To get the type of behavior you are looking for, you should be able to use the new "Selection Rules" section of the trailers config. That will let you match by "Genre" and "Year" or "Genre" and "Decade" when the plugin is selecting trailers. I added more details in the project's readme in regards to all the new features.
